AllCops:
  NewCops: disable
  TargetRubyVersion: 3.0.0

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Metrics:
  Enabled: false

Layout/LineLength:
  Max: 120
