name: Ruby

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and test

    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2

    - name: Install dependencies
      run: bundle install

    - name: Run tests
      run: bundle exec rspec

  rubocop:
    runs-on: ubuntu-latest
    name: Run rubocop

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2

      - name: Install dependencies
        run: bundle install

      - name: Run RuboCop
        run: bundle exec rubocop
